<?php

namespace App\Mailer;

use App\Entity\User;
use \Swift_SmtpTransport;
use \Swift_Mailer;
use \Swift_Message;

class Mailer
{
    /**
    * @var \Swift_Mailer
    */
    private $mailer;

    /**
    * @var \Twig_Environment
    */
    private $twig;

    public function __construct(
        \Swift_Mailer $mailer,
        \Twig_Environment $twig,
        string $mailFrom
    ) {
        $this->mailer = $mailer;
        $this->twig = $twig;
        $this->mailFrom = $mailFrom;
        //$this->mailUser = '%env(string:MAILER_USER)%';
    }

    public function sendConfirmationEmail(User $user)
    {
        $transport = (new Swift_SmtpTransport('smtp.mailtrap.io', 2525))
          ->setUsername('9c69f22c84d53b') // generated by Mailtrap
          //->setUsername($this->mailUser)
          ->setPassword('0c08a8f7fbc02e') // generated by Mailtrap
          ;
        $this->mailer = new Swift_Mailer($transport);
        $body = $this->twig->render('email/registration.html.twig', [
      'user' => $user,
        ]);
        $message = (new Swift_Message())
                ->setSubject('Welcome to the micro-post app')
                ->setFrom($this->mailFrom)
                ->setTo($user->getEmail())
                ->setBody($body, 'text/html');

        $this->mailer->send($message);
    }
}
